// frontend/src/app/AppSidebar.tsx
import { useSyncExternalStore } from 'react'
import { useLocation } from 'react-router'
import { SemanticIcon, semanticLabel, type UiObjectKey } from '@/foundation/semanticRegistry'
import { statusLabel } from '@/utils/displayLabels'
import { PageLink } from '@/pages/w2/shared'
import type { ApplicationOwnership } from './ownership'

const navigation: Array<[string, UiObjectKey]> = [
  ['/', 'nav.home'], ['/projects', 'nav.projects'], ['/knowledge', 'nav.knowledge'], ['/ppt', 'nav.ppt'], ['/requirements', 'nav.requirements'], ['/workflows', 'nav.workflows'], ['/designs', 'nav.designs'], ['/tasks', 'nav.tasks'], ['/inbox', 'nav.inbox'], ['/insights', 'nav.insights'], ['/template-tasks', 'nav.templateTasks'],
]
const system: Array<[string, UiObjectKey]> = [['/runtime', 'nav.runtime'], ['/tools', 'nav.tools'], ['/databases', 'nav.databases'], ['/roles', 'nav.roles'], ['/settings', 'nav.settings']]
export function AppSidebar({ application }: { application: ApplicationOwnership }) {
  const location = useLocation(), path = location.pathname + location.search + location.hash
  const task = useSyncExternalStore(application.task.subscribe, application.task.getSnapshot, application.task.getSnapshot)
  const {knowledgePath}=useSyncExternalStore(application.subscribeNavigation,application.getNavigationSnapshot,application.getNavigationSnapshot)
  const appNavigation = {
    go: async (to: import('@/pages/w2/shared/types').W2Target, replace?: boolean) => {
      const current = application.current
      if (current?.active) return current.navigation.go(to, replace)
      await application.driver?.navigate(typeof to === 'string' ? to : to.path, { replace }); return application.healthy
    },
  } as import('@/pages/w2/shared/types').W2Navigation
  const link = (to: string, key: UiObjectKey) => <PageLink key={to} to={to === '/knowledge' ? knowledgePath : to} navigation={appNavigation} className={`nav-item${(to === '/' ? path === '/' : location.pathname.startsWith(to)) ? ' router-link-active' : ''}`}><SemanticIcon semanticKey={key} /><span>{semanticLabel(key)}</span></PageLink>
  return <aside className="app-sidebar">
    <PageLink className="brand" to="/" navigation={appNavigation} aria-label="OpenCode Loopper 首页"><span className="brand-mark"><SemanticIcon semanticKey="nav.tasks" /></span><span className="brand-copy">OpenCode Loopper<small>本地控制台</small></span></PageLink>
    <p className="nav-label">工作区</p><nav aria-label="主导航">{navigation.map(([to, key]) => link(to, key))}</nav>
    <p className="nav-label">系统</p><nav aria-label="系统导航">{system.map(([to, key]) => link(to, key))}</nav>
    <div className="sidebar-spacer" /><PageLink className="runtime-mini" to="/runtime" navigation={appNavigation}>
      <div className="runtime-mini-title"><span>OpenCode 运行环境</span><span className={`status-badge ${!task.runtime ? 'status-pending' : task.runtime.status === 'ONLINE' ? 'status-success' : 'status-danger'}`}>{task.runtime ? statusLabel(task.runtime.status) : '未检查'}</span></div><strong>{task.runtime?.model ?? '等待连接'}</strong>
    </PageLink>
  </aside>
}

// frontend/src/components/AppSidebar.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { storeToRefs } from 'pinia'
import { useTaskStore } from '@/stores/taskStore'
import { statusLabel } from '@/utils/displayLabels'

const taskStore = useTaskStore()
const { runtime } = storeToRefs(taskStore)

const navigation = [
  { to: '/', icon: 'lucide:house', label: '主页' },
  { to: '/projects', icon: 'lucide:folder-kanban', label: '项目' },
  { to: '/knowledge', icon: 'lucide:book-open', label: '知识库' },
  { to: '/designer', icon: 'lucide:sparkles', label: '设计与执行规范' },
  { to: '/designs', icon: 'lucide:history', label: '历史设计' },
  { to: '/tasks', icon: 'lucide:orbit', label: '任务' },
  { to: '/inbox', icon: 'lucide:inbox', label: '待处理中心' },
  { to: '/insights', icon: 'lucide:chart-no-axes-combined', label: '质量与用量' },
  { to: '/template-tasks', icon: 'lucide:workflow', label: '模板任务' },
]
</script>

<template>
  <aside class="app-sidebar">
    <RouterLink class="brand" to="/" aria-label="OpenCode Loopper 首页">
      <span class="brand-mark"><Icon icon="lucide:orbit" /></span>
      <span class="brand-copy">OpenCode Loopper<small>本地控制台</small></span>
    </RouterLink>

    <p class="nav-label">工作区</p>
    <nav aria-label="主导航">
      <RouterLink v-for="item in navigation" :key="item.to" class="nav-item" :to="item.to">
        <Icon :icon="item.icon" width="17" />
        <span>{{ item.label }}</span>
      </RouterLink>
    </nav>

    <p class="nav-label">系统</p>
    <nav aria-label="系统导航">
      <RouterLink class="nav-item" to="/runtime"><Icon icon="lucide:cpu" width="17" /><span>运行环境</span></RouterLink>
      <RouterLink class="nav-item" to="/tools"><Icon icon="lucide:wrench" width="17" /><span>工具与 Skill</span></RouterLink>
      <RouterLink class="nav-item" to="/databases"><Icon icon="lucide:database" width="17" /><span>数据库</span></RouterLink>
      <RouterLink class="nav-item" to="/settings"><Icon icon="lucide:settings-2" width="17" /><span>设置</span></RouterLink>
    </nav>

    <div class="sidebar-spacer" />
    <RouterLink class="runtime-mini" to="/runtime">
      <div class="runtime-mini-title"><span>OpenCode 运行环境</span><span :class="['status-badge', !runtime ? 'status-pending' : runtime.status === 'ONLINE' ? 'status-success' : 'status-danger']">{{ runtime ? statusLabel(runtime.status) : '未检查' }}</span></div>
      <strong>{{ runtime?.model ?? '等待连接' }}</strong>
    </RouterLink>
  </aside>
</template>
